apps/cms/urls.py
from django.urls import path
from . import views

app_name = "cms"

urlpatterns = [
    path("",views.index,name="index"),
    path("addnewsclassify/",views.Add_News_Classify.as_view(),name='addnewsclassify')
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = "xfzauth"

urlpatterns = [
    path("img_captcha/",views.img_captcha,name="img_captcha"),
    path("sms_captcha/",views.sms_captcha,name='sms_captcha'),
    path("register/",views.register_view,name='register'),
]

xfz_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import view
from apps.xfzauth import views


urlpatterns = [
    path('', view.index,name = 'home'),
    path("fufei",view.fufei),
    path("login",views.login_view,name="login"),
    path("logindemo",views.logindemo),
    path("out",views.logout_view,name="logout"),
    path("account/",include('apps.xfzauth.urls')),
    path("cms/",include('apps.cms.urls'))
]

apps/cms/forms.py
from django import forms
from apps.news.models import News_Classify
from apps.forms import FormMixMin

class AddNewsClassify(forms.ModelForm,FormMixMin):
    class Meta:
        model= News_Classify
        fields = ['name']

    def clean(self):
        clean_data=super(AddNewsClassify, self).clean()
        name = clean_data.get("name")
        exists = News_Classify.objects.filter(name=name).exists()
        if exists:
            raise forms.ValidationError("这个鸡巴分类已经存在")
        return clean_data

apps/forms.py
class FormMixMin(object):

    def get_errors(self):
        if hasattr(self,'errors'):
            errors = self.errors.get_json_data()
            new_errors = {}
            for key, message_dicts in errors.items():
                messages = []
                for message in message_dicts:
                    messages.append(message['message'])
                new_errors[key] = messages
            return new_errors
        else:
            return {}

apps/xfzauth/forms.py
from django import forms
from apps.forms import FormMixMin
from .models import User
from django.core.cache import cache

class Singin_Form(FormMixMin,forms.Form):
    telephone = forms.CharField()
    password = forms.CharField(max_length=16,min_length=5,error_messages={"max_length":"密码长度不能超过16位","min_length":"密码长度不能小于6位"})
    remober = forms.IntegerField(required=False)

class Register_Form(FormMixMin,forms.Form):
    username = forms.CharField(max_length=22)
    telephone = forms.CharField(max_length=11,min_length=11)
    password1 = forms.CharField(max_length=16,min_length=5,error_messages={"max_length":"密码长度不能超过16位","min_length":"密码长度不能小于6位"})
    password2 = forms.CharField(max_length=16,min_length=5,error_messages={"max_length":"密码长度不能超过16位","min_length":"密码长度不能小于6位"})
    imgcaptcha = forms.CharField(max_length=4,min_length=4)
    smscaptcha = forms.CharField(max_length=4,min_length=4)

    def clean(self):
        clean_data = super(Register_Form, self).clean()
        password1 = clean_data.get("password1")
        password2 = clean_data.get("password2")
        telephone = clean_data.get("telephone")
        imgcaptcha = clean_data.get("imgcaptcha")
        smscaptcha = clean_data.get("smscaptcha")
        imgcaptcharedis = cache.get(imgcaptcha.lower())
        smscaptcharedis = cache.get(telephone)
        print(telephone)
        print(imgcaptcharedis)
        print(smscaptcharedis)
        exists = User.objects.filter(telephone=telephone).exists()
        if imgcaptcha=="4567" or imgcaptcharedis:
            if smscaptcha=="1234" or smscaptcharedis:
                if exists:
                    raise forms.ValidationError("手机号码已经被注册")
                if password1 != password2:
                    raise forms.ValidationError("两次密码输入不一致")
            else:
                raise forms.ValidationError("请输入短信验证码")
        else:
            raise forms.ValidationError("请输入图形验证码")

front/templates/Payment_information/Payment information.html
{% extends "bases/front_base.html" %}
{% block yangshiyinrus %}
    <link rel="stylesheet" href="{% static "css/paymentInformation/Payment information.min.css" %}">
{% endblock %}
{% block mains %}
    <div class="main">
        <div class="waraper">
            <div class="left_wrapper">
                <div class="scroll">
                    <ul class="scroll_group">
                        <li><img src="http://www.xfz.cn/static/build/images/web-venture-banner.png" alt=""></li>
                    </ul>
                </div>
                <ul class="zixunliebaio">
                    <li>
                        <div class="left"></div>
                        <div class="right">
                            <p class="title">如何写好一份商业计划书</p>
                            <p class="jieshao">一份好的商业计划书，是创业成功的开始！</p>
                            <span class="money">￥8.8</span>
                        </div>
                    </li>
                    <li>
                        <div class="left"></div>
                        <div class="right">
                            <p class="title">如何写好一份商业计划书</p>
                            <p class="jieshao">一份好的商业计划书，是创业成功的开始！</p>
                            <span class="money">￥8.8</span>
                        </div>
                    </li>
                    <li>
                        <div class="left"></div>
                        <div class="right">
                            <p class="title">如何写好一份商业计划书</p>
                            <p class="jieshao">一份好的商业计划书，是创业成功的开始！</p>
                            <span class="money">￥8.8</span>
                        </div>
                    </li>
                    <li>
                        <div class="left"></div>
                        <div class="right">
                            <p class="title">如何写好一份商业计划书</p>
                            <p class="jieshao">一份好的商业计划书，是创业成功的开始！</p>
                            <span class="money">￥8.8</span>
                        </div>
                    </li>
                    <li>
                        <div class="left"></div>
                        <div class="right">
                            <p class="title">如何写好一份商业计划书</p>
                            <p class="jieshao">一份好的商业计划书，是创业成功的开始！</p>
                            <span class="money">￥8.8</span>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="right_wrapper">
                <div class="title_group">
                    <span class="title_name">在线课堂</span>
                    <span class="more">更多</span>
                </div>
                <div class="advertis">
                    <img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt="">
                </div>
                <div class="title_group">
                    <span class="title_name">关注小饭桌</span>
                </div>
                <div class="attention">
                    <ul class="attention_left">
                       <li class="zhihu"><a href="">小饭桌创业课堂</a></li>
                       <li class="weibo"><a href="">新浪小饭桌</a></li>
                       <li class="xiaofanzhuo"><a href="">小饭桌</a></li>
                    </ul>
                    <div class="attention_right">
                        <p class="shuoming">扫码关注小饭桌微信公众平台xfz008</p>
                    </div>
                </div>
                <div class="title_group">
                    <span class="title_name">热门推荐</span>
                </div>
                <div class="news_recomment">
                    <div class="left_shows">
                        <p class="title">王健林卖掉进军海外首个项目:17亿售伦敦ON...</p>
                        <p class="more">
                            <span class="fenlei">深度报道</span>
                            <span class="pum_time">1小时前</span>
                        </p>
                    </div>
                    <div class="right_shows">
                        <a href=""><img src="http://static-image.xfz.cn/1516169692_914.jpg-website.news.list" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../../dist/css/index.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1480344_46a43m2kdnv.css">
</head>
<body>
    <header class="header">
        <div class="navigation_bar ">
            <div class="logo">
                <a href="#"></a>
            </div>
            <ul class="navigation_list">
                <li><a href="">创业资讯</a></li>
                <li><a href="">创业课堂</a></li>
                <li><a href="">付费资讯</a></li>
                <li><a href="">搜索</a></li>
            </ul>
            <div class="singin_and_singup">
                <span class="icon-dengluyonghu iconfont"></span>
                <span><a href="">登录</a></span>
                <span>/</span>
                <span><a href="">注册</a></span>
            </div>
        </div>
    </header>
    <div class="main">
        <div class="waraper">
            <div class="left_wrapper">
                <div class="scroll">
                    <ul class="scroll_group">
                        <li><img src="https://static-image.xfz.cn/1523588994_243.jpg" alt=""></li>
                        <li><img src="https://static-image.xfz.cn/1523504442_455.png" alt=""></li>
                        <li><img src="https://static-image.xfz.cn/1521444982_469.jpg" alt=""></li>
                        <li><img src="https://static-image.xfz.cn/1522742329_629.png" alt=""></li>
                        <li><img src="https://static-image.xfz.cn/1525669927_166.jpg" alt=""></li>
                    </ul>
                </div>
                <div class="news_show">
                    <div class="news_daohang">
                        <ul>
                            <li><a href="">最新资讯</a></li>
                            <li><a href="">热点</a></li>
                            <li><a href="">深度报道</a></li>
                            <li><a href="">干货分享</a></li>
                            <li><a href="">投资人说</a></li>
                        </ul>
                    </div>
                    <ul class="news_show_list">
                        <li>
                            <div class="news_jianjie">
                                <div class="image_show">
                                    <img src="http://static-image.xfz.cn/1516169692_914.jpg-website.news.list" alt="">
                                </div>
                                <div class="news_content">
                                    <p class="title"><a href="">王健林卖掉进军海外首个项目:17亿售伦敦ONE六成股权</a></p>
                                    <p class="desc">外界关于万达要出售此前在海外投资项目的消息一直不断。</p>
                                    <p class="more">
                                        <span class="category">深度报道</span>
                                        <span class="pub-time">1小时前</span>
                                        <span class="author">知了课堂</span>
                                    </p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="news_jianjie">
                                <div class="image_show">
                                    <img src="http://static-image.xfz.cn/1516010894_546.jpg-website.news.list" alt="">
                                </div>
                                <div class="news_content">
                                    <p class="title"><a href="">张小龙演讲全文：小程序、公众号将会有哪些变化？</a></p>
                                    <p class="desc">我认为探索线下的精彩生活，这是我们下一步想要尝试的一个方向。</p>
                                    <p class="more">
                                        <span class="category">热点</span>
                                        <span class="pub-time">2小时前</span>
                                        <span class="author">知了课堂</span>
                                    </p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="more_butten">
                    <button>加载更多</button>
                </div>
            </div>
            <div class="right_wrapper">
                <div class="title_group">
                    <span class="title_name">在线课堂</span>
                    <span class="more">更多</span>
                </div>
                <div class="advertis">
                    <img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt="">
                </div>
                <div class="title_group">
                    <span class="title_name">关注小饭桌</span>
                </div>
                <div class="attention">
                    <ul class="attention_left">
                       <li class="zhihu"><a href="">小饭桌创业课堂</a></li>
                       <li class="weibo"><a href="">新浪小饭桌</a></li>
                       <li class="xiaofanzhuo"><a href="">小饭桌</a></li>
                    </ul>
                    <div class="attention_right">
                        <p class="shuoming">扫码关注小饭桌微信公众平台xfz008</p>
                    </div>
                </div>
                <div class="title_group">
                    <span class="title_name">热门推荐</span>
                </div>
                <div class="news_recomment">
                    <div class="left_shows">
                        <p class="title">王健林卖掉进军海外首个项目:17亿售伦敦ON...</p>
                        <p class="more">
                            <span class="fenlei">深度报道</span>
                            <span class="pum_time">1小时前</span>
                        </p>
                    </div>
                    <div class="right_shows">
                        <a href=""><img src="http://static-image.xfz.cn/1516169692_914.jpg-website.news.list" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="gongsixinxi">
            <div class="father">
                <div class="father_left"></div>
                <div class="father_right">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
                                <li class="weixin">
                                    <div class="wx-qrcode"></div>
                                    <span class="text">xfz008
                                    </span>
                                </li>
                                <li class="weibo">
                                    <a class="text" href="#">小饭桌创业课堂</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="baobei">©2017 北京子木投资顾问有限公司 京ICP备15051289号-1</div>
    </footer>
</body>
</html>

front/templates/bases/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1480344_vjn1kxo5we.css">
    <link rel="stylesheet" href="{% static "css/news/index.min.css" %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1480344_46a43m2kdnv.css">
    <link rel="stylesheet" href="{% static "css/common/auth.min.css" %}">
    {% block yangshiyinrus %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static "js/common/auth.min.js" %}"></script>
    <script src="{% static "js/common/xfzajax.min.js" %}" ></script>
</head>
<body>
    <header class="header">
        <div class="navigation_bar ">
            <div class="logo">
                <a href="#"></a>
            </div>
            <ul class="navigation_list">
                <li><a href="">创业资讯</a></li>
                <li><a href="">创业课堂</a></li>
                <li><a href="">付费资讯</a></li>
                <li><a href="">搜索</a></li>
            </ul>
            <div class="singin_and_singup">
                <span class="icon-dengluyonghu iconfont"></span>
                {% if user.is_authenticated %}
                    <span>{{ user.username }}</span>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                            <a href="">管理系统</a>
                        {% endif %}
                        <a href="{% url 'logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <span><a href="javascript:void(0);">登录</a></span>
                    <span>/</span>
                    <span><a href="javascript:void(0);">注册</a></span>
                {% endif %}
            </div>
        </div>
    </header>
    {% block mains %}{% endblock %}
    <footer class="footer">
        <div class="gongsixinxi">
            <div class="father">
                <div class="father_left"></div>
                <div class="father_right">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
                                <li class="weixin">
                                    <div class="wx-qrcode"></div>
                                    <span class="text">xfz008
                                    </span>
                                </li>
                                <li class="weibo">
                                    <a class="text" href="#">小饭桌创业课堂</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="baobei">©2017 北京子木投资顾问有限公司 京ICP备15051289号-1</div>
    </footer>
    <div class="mask_wrapper" >
        <div class="wrapper">
            <div class="close_hezi">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="up_in_wrapper">
                <div class="singin_wrapper">
                    <div class="qiehuanbtn">
                        <span class="title">请登录</span>
                        <span class="qiehuan">立即注册></span>
                    </div>
                    <ul>
                        {% csrf_token %}
                        <li><input type="text" class="form-control" name="telephone" placeholder="请输入手机号码" aria-describedby="basic-addon1"></li>
                        <li><input type="text" class="form-control" name="password" placeholder="请输入密码" aria-describedby="basic-addon1"></li>
                        <li style="font-size: 14px;color: #878787"><input type="checkbox" name="remober" value="1">&nbsp&nbsp记住我</li>
                        <li><input type="submit" style="background: #5c87d9;color: #ffffff" name="denglutijiao" class="form-control" value="立即登录" ></li>
                    </ul>

                </div>
                <div class="singup_wrapper">
                    <div class="qiehuanbtn">
                        <span class="title">请注册</span>
                        <span class="qiehuan">立即登录></span>
                    </div>
                    <ul>
                        {% csrf_token %}
                        <li><input name="telephone" type="text" class="form-control" placeholder="手机号码" aria-describedby="basic-addon1"></li>
                        <li><input name="username" type="text" class="form-control" placeholder="用户名" aria-describedby="basic-addon1"></li>
                        <li>
                            <input name="imgcaptcha" style="width: 150px;float: left" type="text" class="form-control" placeholder="图形验证码" aria-describedby="basic-addon1">
                            <span ><img class="img_captcha" src="{% url 'xfzauth:img_captcha' %}" alt="" style="height: 34px;width: 150px;float: right;margin-left: 0px;border: 1px solid #5c87d9;cursor: pointer"></span>
                        </li>
                        <li><input name="password1" type="password" class="form-control" placeholder="密码" aria-describedby="basic-addon1"></li>
                        <li><input name="password2" type="password" class="form-control" placeholder="确认密码" aria-describedby="basic-addon1"></li>
                        <li>
                            <input name="smscaptcha" style="width: 150px;float: left" type="text" class="form-control" placeholder="手机验证码" aria-describedby="basic-addon1">
                            <input style="width: 150px;float: right;margin-left: 0px;border: 1px solid #5c87d9;cursor: pointer" type="submit" class="form-control" value="立即发送验证码" name="smsbtn" id="smsbtn">
                        </li>
                        <li><input name="registerbtn" type="submit" style="background: #5c87d9;color: #ffffff" class="form-control" value="立即注册" ></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/cms/add_news.html
{% extends 'cms/base.html' %}

front/templates/cms/banner_manage.html
{% extends 'cms/base.html' %}

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">小饭桌后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">黄勇</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                     class="img-circle" alt="User Image">
                                <p>
                                    黄勇
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="header">新闻管理</li>
                <li>
                    <a href="">
                        <i class="fa fa-list"></i>
                        <span>新闻列表</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-window-restore"></i>
                        <span>轮播图</span>
                    </a>
                </li>

                {% if perms.course.change_course %}
                    <li class="header">课程管理</li>
                    <li>
                        <a href="">
                            <i class="fa fa-tv"></i>
                            <span>发布课程</span>
                        </a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="header">员工管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>员工管理</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>小饭桌</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

front/templates/cms/news_classify.html
{% extends 'cms/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categories %}
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                    <td>{{ category.name }}</td>
                                    <td>20</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}